logging:
  level:
      com.am.es: DEBUG
server:
  port: 8088
spring:
  datasource:
    ds1:
      jdbc-url: jdbc:mysql://rm-bp1fd159l08pvu616.mysql.rds.aliyuncs.com:3306/crmclues?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: Aomengzhibo45678!
      driver-class-name: com.mysql.jdbc.Driver
    ds2:
      jdbc-url: jdbc:mysql://rm-bp1fd159l08pvu616.mysql.rds.aliyuncs.com:3306/crmorder?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: Aomengzhibo45678!
      driver-class-name: com.mysql.jdbc.Driver

  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
      cluster-name: clues-crm
      repositories:
        enabled: true

aliyun:
  accessKey: LTAIbvZWdIjgY3QE
  secretKey: 9rsz1EFMwO2anQDhBlMjbL2RHRlJR2
  tag: alldream
  topic: am_crm_es
  onsAddr: http://onsaddr-internet.aliyun.com/rocketmq/nsaddr4client-internet
  sendMsgTimeoutMillis: 3000
  suspendTimeMillis: 100
  maxReconsumeTimes: 20